from __future__ import annotations

from enum import Enum


class RoleEnum(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    TENANT_ADMIN = "TENANT_ADMIN"
    INVENTORY_MANAGER = "INVENTORY_MANAGER"
    SALES_STAFF = "SALES_STAFF"
    PURCHASE_STAFF = "PURCHASE_STAFF"
    VIEWER = "VIEWER"


class TenantStatusEnum(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class UserStatusEnum(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class RecordStatusEnum(str, Enum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class InventoryTransactionTypeEnum(str, Enum):
    STOCK_IN = "STOCK_IN"
    STOCK_OUT = "STOCK_OUT"
    ADJUSTMENT = "ADJUSTMENT"
    TRANSFER_IN = "TRANSFER_IN"
    TRANSFER_OUT = "TRANSFER_OUT"
    SALES_ORDER_RESERVE = "SALES_ORDER_RESERVE"
    SALES_ORDER_DEDUCT = "SALES_ORDER_DEDUCT"
    SALES_ORDER_CANCEL_RELEASE = "SALES_ORDER_CANCEL_RELEASE"
    PURCHASE_RECEIVE = "PURCHASE_RECEIVE"
    RETURN_IN = "RETURN_IN"
    DAMAGE_OUT = "DAMAGE_OUT"


class StockTransferStatusEnum(str, Enum):
    DRAFT = "DRAFT"
    IN_TRANSIT = "IN_TRANSIT"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
