import {
  ArrowLeft,
  Activity,
  AlertTriangle,
  Bell,
  Blocks,
  BookText,
  Box,
  BriefcaseBusiness,
  Building2,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Clock3,
  Cog,
  FileBarChart2,
  FileText,
  Filter,
  Grip,
  HandCoins,
  Hash,
  HelpCircle,
  Home,
  Import,
  LayoutDashboard,
  Layers3,
  Lightbulb,
  Menu,
  MoreHorizontal,
  Package,
  PackagePlus,
  Plug,
  Plus,
  Receipt,
  Search,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Star,
  Truck,
  Undo2,
  UserCircle2,
  UserCog,
  Users,
  Warehouse,
} from "lucide-react";

const icons = {
  arrowLeft: ArrowLeft,
  activity: Activity,
  alert: AlertTriangle,
  avatar: UserCircle2,
  bell: Bell,
  bill: Receipt,
  blocks: Blocks,
  book: BookText,
  box: Box,
  briefcase: BriefcaseBusiness,
  building: Building2,
  cart: ShoppingCart,
  chart: FileBarChart2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  clipboard: ClipboardList,
  clock: Clock3,
  dashboard: LayoutDashboard,
  export: Import,
  file: FileText,
  filter: Filter,
  hash: Hash,
  help: HelpCircle,
  home: Home,
  import: Import,
  layers: Layers3,
  lightbulb: Lightbulb,
  menu: Menu,
  more: MoreHorizontal,
  package: Package,
  plug: Plug,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  settings: Cog,
  shield: ShieldCheck,
  shuffle: Grip,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  stars: Star,
  truck: Truck,
  undo: Undo2,
  userCog: UserCog,
  users: Users,
  warehouse: Warehouse,
  money: HandCoins,
  packagePlus: PackagePlus,
};

export function Icon({ name, size = 18, className = "" }) {
  const Component = icons[name] ?? LayoutDashboard;
  return <Component className={className} size={size} strokeWidth={1.9} aria-hidden="true" />;
}
