export const resourceConfigs = {
  products: {
    title: "Items",
    description: "Track products, stock posture, reorder levels, and pricing from a single dense inventory list.",
    endpoint: "/products",
    createPath: "/items/new",
    createLabel: "+ New Item",
    detailPath: (id) => `/items/${id}`,
    searchPlaceholder: "Search items by name, SKU, or barcode",
    filters: [
      { label: "All Items", value: "all" },
      { label: "Active Items", value: "ACTIVE" },
      { label: "Archived Items", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "sku", label: "SKU" },
      { key: "unit", label: "Unit" },
      { key: "cost_price", label: "Cost Price", kind: "currency" },
      { key: "selling_price", label: "Selling Price", kind: "currency" },
      { key: "reorder_level", label: "Reorder Level" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  warehouses: {
    title: "Warehouses",
    description: "Monitor active stock locations, warehouse managers, and default fulfillment sites.",
    endpoint: "/warehouses",
    detailPath: (id) => `/warehouses/${id}`,
    searchPlaceholder: "Search warehouse name, city, or manager",
    filters: [
      { label: "All Warehouses", value: "all" },
      { label: "Active Warehouses", value: "ACTIVE" },
      { label: "Archived Warehouses", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Warehouse" },
      { key: "code", label: "Code" },
      { key: "city", label: "City" },
      { key: "manager_name", label: "Manager" },
      { key: "is_default", label: "Primary", kind: "boolean" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  vendors: {
    title: "Vendors",
    description: "Keep supplier records ready for procurement, receiving, and replenishment planning.",
    endpoint: "/vendors",
    searchPlaceholder: "Search vendors by name, email, or GST number",
    filters: [
      { label: "All Vendors", value: "all" },
      { label: "Active Vendors", value: "ACTIVE" },
      { label: "Archived Vendors", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Vendor" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "gst_number", label: "GST" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  customers: {
    title: "Customers",
    description: "Maintain customer contact records for sales, dispatch, and follow-up workflows.",
    endpoint: "/customers",
    searchPlaceholder: "Search customers by name, email, or GST number",
    filters: [
      { label: "All Customers", value: "all" },
      { label: "Active Customers", value: "ACTIVE" },
      { label: "Archived Customers", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Customer" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "gst_number", label: "GST" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  inventoryTransactions: {
    title: "Inventory Transactions",
    description: "Review every stock movement with type, warehouse, quantity, and reference context.",
    endpoint: "/inventory/transactions",
    searchPlaceholder: "Search by reference, product, or movement type",
    filters: [
      { label: "All Transactions", value: "all" },
      { label: "Stock In", value: "STOCK_IN" },
      { label: "Stock Out", value: "STOCK_OUT" },
      { label: "Adjustment", value: "ADJUSTMENT" },
      { label: "Transfer In", value: "TRANSFER_IN" },
      { label: "Transfer Out", value: "TRANSFER_OUT" },
      { label: "Purchase Receive", value: "PURCHASE_RECEIVE" },
      { label: "Sales Deduct", value: "SALES_ORDER_DEDUCT" },
    ],
    columns: [
      { key: "transaction_type", label: "Type", kind: "status" },
      { key: "product_id", label: "Product" },
      { key: "warehouse_id", label: "Warehouse" },
      { key: "quantity", label: "Quantity" },
      { key: "reference_type", label: "Reference" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  stockTransfers: {
    title: "Stock Transfers",
    description: "Move stock across locations while keeping transfer ownership and state visible.",
    endpoint: "/inventory/transfers",
    searchPlaceholder: "Search transfer number or transfer notes",
    filters: [
      { label: "All Transfers", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "In Transit", value: "IN_TRANSIT" },
      { label: "Completed", value: "COMPLETED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "id", label: "Transfer #" },
      { key: "source_warehouse_id", label: "Source" },
      { key: "destination_warehouse_id", label: "Destination" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_by", label: "Owner" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  purchaseOrders: {
    title: "Purchase Orders",
    description: "Track issue, receipt, and partial receipt progress across inbound vendor orders.",
    endpoint: "/purchase-orders",
    createPath: "/purchase-orders/new",
    createLabel: "+ New Purchase Order",
    detailPath: (id) => `/purchase-orders/${id}`,
    searchPlaceholder: "Search PO number or vendor",
    filters: [
      { label: "All Purchase Orders", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Issued", value: "ISSUED" },
      { label: "Partially Received", value: "PARTIALLY_RECEIVED" },
      { label: "Received", value: "RECEIVED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "po_number", label: "PO Number" },
      { key: "vendor_id", label: "Vendor" },
      { key: "order_date", label: "Order Date", kind: "date" },
      { key: "total_amount", label: "Amount", kind: "currency" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  salesOrders: {
    title: "Sales Orders",
    description: "Monitor the order flow from draft through delivery with clear status visibility.",
    endpoint: "/sales-orders",
    createPath: "/sales-orders/new",
    createLabel: "+ New Sales Order",
    detailPath: (id) => `/sales-orders/${id}`,
    searchPlaceholder: "Search SO number or customer",
    filters: [
      { label: "All Sales Orders", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Confirmed", value: "CONFIRMED" },
      { label: "Packed", value: "PACKED" },
      { label: "Shipped", value: "SHIPPED" },
      { label: "Delivered", value: "DELIVERED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "so_number", label: "SO Number" },
      { key: "customer_id", label: "Customer" },
      { key: "order_date", label: "Order Date", kind: "date" },
      { key: "total_amount", label: "Amount", kind: "currency" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  users: {
    title: "Users",
    description: "Review workspace users, roles, account status, and last-login visibility.",
    endpoint: "/users",
    searchPlaceholder: "Search users by name or email",
    filters: [
      { label: "All Users", value: "all" },
      { label: "Active Users", value: "ACTIVE" },
      { label: "Inactive Users", value: "INACTIVE" },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role", kind: "status" },
      { key: "status", label: "Status", kind: "status" },
      { key: "last_login_at", label: "Last Login", kind: "date" },
    ],
  },
  tenants: {
    title: "Tenants",
    description: "Super admin view of tenant companies, plans, and activation status.",
    endpoint: "/tenants",
    searchPlaceholder: "Search tenant name or contact email",
    filters: [
      { label: "All Tenants", value: "all" },
      { label: "Active Tenants", value: "ACTIVE" },
      { label: "Disabled Tenants", value: "DISABLED" },
    ],
    columns: [
      { key: "company_name", label: "Company" },
      { key: "contact_email", label: "Contact Email" },
      { key: "business_type", label: "Business Type" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  auditLogs: {
    title: "Audit Logs",
    description: "Trace backend actions, entity changes, and operator activity across the workspace.",
    endpoint: "/audit-logs",
    searchPlaceholder: "Search action or entity type",
    filters: [{ label: "All Logs", value: "all" }],
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_type", label: "Entity" },
      { key: "entity_id", label: "Entity ID" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
};

export const reportCatalog = [
  { key: "inventory-summary", label: "Inventory Summary", endpoint: "/reports/inventory-summary" },
  { key: "stock-movement", label: "Stock Movement", endpoint: "/reports/stock-movement" },
  { key: "low-stock", label: "Low Stock", endpoint: "/reports/low-stock" },
  { key: "warehouse-stock", label: "Warehouse Stock", endpoint: "/reports/warehouse-stock" },
  { key: "product-valuation", label: "Product Valuation", endpoint: "/reports/product-valuation" },
  { key: "purchase-orders", label: "Purchase Orders", endpoint: "/reports/purchase-orders" },
  { key: "sales-orders", label: "Sales Orders", endpoint: "/reports/sales-orders" },
];
