export const resourceConfigs = {
  categories: {
    title: "Categories",
    description: "Manage tenant-specific item categories for filtering, reporting, and catalog structure.",
    endpoint: "/categories",
    createPath: "/categories/new",
    createLabel: "+ New Category",
    detailPath: (id) => `/categories/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search categories by name or description",
    filters: [
      { label: "All Categories", value: "all" },
      { label: "Active Categories", value: "ACTIVE" },
      { label: "Archived Categories", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Category" },
      { key: "description", label: "Description" },
      { key: "status", label: "Status", kind: "status" },
      { key: "updated_at", label: "Updated", kind: "date" },
    ],
  },
  brands: {
    title: "Brands",
    description: "Manage brand master data used by the product catalog and reporting filters.",
    endpoint: "/brands",
    createPath: "/brands/new",
    createLabel: "+ New Brand",
    detailPath: (id) => `/brands/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search brands by name or description",
    filters: [
      { label: "All Brands", value: "all" },
      { label: "Active Brands", value: "ACTIVE" },
      { label: "Archived Brands", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Brand" },
      { key: "description", label: "Description" },
      { key: "status", label: "Status", kind: "status" },
      { key: "updated_at", label: "Updated", kind: "date" },
    ],
  },
  products: {
    title: "Items",
    description: "Track products, stock posture, reorder levels, and pricing from a single dense inventory list.",
    endpoint: "/products",
    createPath: "/items/new",
    createLabel: "+ New Item",
    detailPath: (id) => `/items/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search items by name, SKU, or barcode",
    filters: [
      { label: "All Items", value: "all" },
      { label: "Active Items", value: "ACTIVE" },
      { label: "Archived Items", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "sku", label: "SKU" },
      { key: "unit", label: "Unit" },
      { key: "cost_price", label: "Cost Price", kind: "currency" },
      { key: "selling_price", label: "Selling Price", kind: "currency" },
      { key: "reorder_level", label: "Reorder Level" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  warehouses: {
    title: "Warehouses",
    description: "Monitor active stock locations, warehouse managers, and default fulfillment sites.",
    endpoint: "/warehouses",
    createPath: "/warehouses/new",
    createLabel: "+ New Warehouse",
    detailPath: (id) => `/warehouses/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search warehouse name, city, or manager",
    filters: [
      { label: "All Warehouses", value: "all" },
      { label: "Active Warehouses", value: "ACTIVE" },
      { label: "Archived Warehouses", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Warehouse" },
      { key: "code", label: "Code" },
      { key: "city", label: "City" },
      { key: "manager_name", label: "Manager" },
      { key: "is_default", label: "Primary", kind: "boolean" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  vendors: {
    title: "Vendors",
    description: "Keep supplier records ready for procurement, receiving, and replenishment planning.",
    endpoint: "/vendors",
    createPath: "/vendors/new",
    createLabel: "+ New Vendor",
    detailPath: (id) => `/vendors/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search vendors by name, email, or GST number",
    filters: [
      { label: "All Vendors", value: "all" },
      { label: "Active Vendors", value: "ACTIVE" },
      { label: "Archived Vendors", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Vendor" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "gst_number", label: "GST" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  customers: {
    title: "Customers",
    description: "Maintain customer contact records for sales, dispatch, and follow-up workflows.",
    endpoint: "/customers",
    createPath: "/customers/new",
    createLabel: "+ New Customer",
    detailPath: (id) => `/customers/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search customers by name, email, or GST number",
    filters: [
      { label: "All Customers", value: "all" },
      { label: "Active Customers", value: "ACTIVE" },
      { label: "Archived Customers", value: "ARCHIVED" },
    ],
    columns: [
      { key: "name", label: "Customer" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "gst_number", label: "GST" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  inventoryTransactions: {
    title: "Inventory Transactions",
    description: "Review every stock movement with type, warehouse, quantity, and reference context.",
    endpoint: "/inventory/transactions",
    searchParam: null,
    filterParam: "transaction_type",
    searchPlaceholder: "Search by reference, product, or movement type",
    filters: [
      { label: "All Transactions", value: "all" },
      { label: "Stock In", value: "STOCK_IN" },
      { label: "Stock Out", value: "STOCK_OUT" },
      { label: "Adjustment", value: "ADJUSTMENT" },
      { label: "Transfer In", value: "TRANSFER_IN" },
      { label: "Transfer Out", value: "TRANSFER_OUT" },
      { label: "Purchase Receive", value: "PURCHASE_RECEIVE" },
      { label: "Sales Deduct", value: "SALES_ORDER_DEDUCT" },
    ],
    columns: [
      { key: "transaction_type", label: "Type", kind: "status" },
      { key: "product_id", label: "Product" },
      { key: "warehouse_id", label: "Warehouse" },
      { key: "quantity", label: "Quantity" },
      { key: "reference_type", label: "Reference" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  stockTransfers: {
    title: "Stock Transfers",
    description: "Move stock across locations while keeping transfer ownership and state visible.",
    endpoint: "/inventory/transfers",
    createPath: "/inventory/transfers/new",
    createLabel: "+ New Transfer",
    detailPath: (id) => `/inventory/transfers/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search transfer number or transfer notes",
    filters: [
      { label: "All Transfers", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "In Transit", value: "IN_TRANSIT" },
      { label: "Completed", value: "COMPLETED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "id", label: "Transfer #" },
      { key: "source_warehouse_id", label: "Source" },
      { key: "destination_warehouse_id", label: "Destination" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_by", label: "Owner" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  purchaseOrders: {
    title: "Purchase Orders",
    description: "Track issue, receipt, and partial receipt progress across inbound vendor orders.",
    endpoint: "/purchase-orders",
    createPath: "/purchase-orders/new",
    createLabel: "+ New Purchase Order",
    detailPath: (id) => `/purchase-orders/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search PO number or vendor",
    filters: [
      { label: "All Purchase Orders", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Issued", value: "ISSUED" },
      { label: "Partially Received", value: "PARTIALLY_RECEIVED" },
      { label: "Received", value: "RECEIVED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "po_number", label: "PO Number" },
      { key: "vendor_id", label: "Vendor" },
      { key: "order_date", label: "Order Date", kind: "date" },
      { key: "total_amount", label: "Amount", kind: "currency" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  salesOrders: {
    title: "Sales Orders",
    description: "Monitor the order flow from draft through delivery with clear status visibility.",
    endpoint: "/sales-orders",
    createPath: "/sales-orders/new",
    createLabel: "+ New Sales Order",
    detailPath: (id) => `/sales-orders/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search SO number or customer",
    filters: [
      { label: "All Sales Orders", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Confirmed", value: "CONFIRMED" },
      { label: "Packed", value: "PACKED" },
      { label: "Shipped", value: "SHIPPED" },
      { label: "Delivered", value: "DELIVERED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "so_number", label: "SO Number" },
      { key: "customer_id", label: "Customer" },
      { key: "order_date", label: "Order Date", kind: "date" },
      { key: "total_amount", label: "Amount", kind: "currency" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  packages: {
    title: "Packages",
    description: "Track fulfillment packages linked to live sales orders and dispatch operations.",
    endpoint: "/packages",
    createPath: "/packages/new",
    createLabel: "+ New Package",
    detailPath: (id) => `/packages/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search package number",
    filters: [
      { label: "All Packages", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Packed", value: "PACKED" },
      { label: "Shipped", value: "SHIPPED" },
      { label: "Delivered", value: "DELIVERED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "package_number", label: "Package #" },
      { key: "sales_order_id", label: "Sales Order" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  invoices: {
    title: "Invoices",
    description: "Manage customer invoices generated from sales orders and their collection stages.",
    endpoint: "/invoices",
    createPath: "/invoices/new",
    createLabel: "+ New Invoice",
    detailPath: (id) => `/invoices/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search invoice number",
    filters: [
      { label: "All Invoices", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Sent", value: "SENT" },
      { label: "Paid", value: "PAID" },
      { label: "Void", value: "VOID" },
    ],
    columns: [
      { key: "invoice_number", label: "Invoice #" },
      { key: "sales_order_id", label: "Sales Order" },
      { key: "invoice_date", label: "Invoice Date", kind: "date" },
      { key: "total_amount", label: "Amount", kind: "currency" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  salesReturns: {
    title: "Sales Returns",
    description: "Capture returned customer quantities and push them back into approved warehouse stock.",
    endpoint: "/sales-returns",
    createPath: "/sales-returns/new",
    createLabel: "+ New Sales Return",
    detailPath: (id) => `/sales-returns/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search sales return number",
    filters: [
      { label: "All Sales Returns", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Received", value: "RECEIVED" },
      { label: "Refunded", value: "REFUNDED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
    columns: [
      { key: "return_number", label: "Return #" },
      { key: "sales_order_id", label: "Sales Order" },
      { key: "return_date", label: "Return Date", kind: "date" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  purchaseReceives: {
    title: "Purchase Receives",
    description: "Post inbound receipts against purchase orders with real warehouse stock updates.",
    endpoint: "/purchase-receives",
    createPath: "/purchase-receives/new",
    createLabel: "+ New Receive",
    detailPath: (id) => `/purchase-receives/${id}`,
    searchParam: "search",
    filterParam: null,
    searchPlaceholder: "Search receipt number",
    filters: [{ label: "All Receipts", value: "all" }],
    columns: [
      { key: "receive_number", label: "Receipt #" },
      { key: "purchase_order_id", label: "Purchase Order" },
      { key: "received_at", label: "Received On", kind: "date" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  bills: {
    title: "Bills",
    description: "Track vendor bills and payable status against purchase orders in one workspace.",
    endpoint: "/bills",
    createPath: "/bills/new",
    createLabel: "+ New Bill",
    detailPath: (id) => `/bills/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search bill number",
    filters: [
      { label: "All Bills", value: "all" },
      { label: "Draft", value: "DRAFT" },
      { label: "Posted", value: "POSTED" },
      { label: "Paid", value: "PAID" },
      { label: "Void", value: "VOID" },
    ],
    columns: [
      { key: "bill_number", label: "Bill #" },
      { key: "purchase_order_id", label: "Purchase Order" },
      { key: "bill_date", label: "Bill Date", kind: "date" },
      { key: "total_amount", label: "Amount", kind: "currency" },
      { key: "status", label: "Status", kind: "status" },
    ],
  },
  users: {
    title: "Users",
    description: "Review workspace users, roles, account status, and last-login visibility.",
    endpoint: "/users",
    createPath: "/users/new",
    createLabel: "+ New User",
    createRoles: ["SUPER_ADMIN", "TENANT_ADMIN"],
    detailPath: (id) => `/users/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search users by name or email",
    filters: [
      { label: "All Users", value: "all" },
      { label: "Active Users", value: "ACTIVE" },
      { label: "Inactive Users", value: "INACTIVE" },
    ],
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "role", label: "Role", kind: "status" },
      { key: "status", label: "Status", kind: "status" },
      { key: "last_login_at", label: "Last Login", kind: "date" },
    ],
  },
  tenants: {
    title: "Tenants",
    description: "Super admin view of tenant companies, plans, and activation status.",
    endpoint: "/tenants",
    createPath: "/tenants/new",
    createLabel: "+ New Tenant",
    createRoles: ["SUPER_ADMIN"],
    detailPath: (id) => `/tenants/${id}`,
    searchParam: "search",
    filterParam: "status",
    searchPlaceholder: "Search tenant name or contact email",
    filters: [
      { label: "All Tenants", value: "all" },
      { label: "Active Tenants", value: "ACTIVE" },
      { label: "Disabled Tenants", value: "DISABLED" },
    ],
    columns: [
      { key: "company_name", label: "Company" },
      { key: "contact_email", label: "Contact Email" },
      { key: "business_type", label: "Business Type" },
      { key: "status", label: "Status", kind: "status" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
  auditLogs: {
    title: "Audit Logs",
    description: "Trace backend actions, entity changes, and operator activity across the workspace.",
    endpoint: "/audit-logs",
    searchParam: null,
    filterParam: null,
    searchPlaceholder: "Search action or entity type",
    filters: [{ label: "All Logs", value: "all" }],
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_type", label: "Entity" },
      { key: "entity_id", label: "Entity ID" },
      { key: "created_at", label: "Created", kind: "date" },
    ],
  },
};

const purchaseOrderStatusOptions = [
  { value: "DRAFT", label: "Draft" },
  { value: "ISSUED", label: "Issued" },
  { value: "PARTIALLY_RECEIVED", label: "Partially Received" },
  { value: "RECEIVED", label: "Received" },
  { value: "CANCELLED", label: "Cancelled" },
];

const salesOrderStatusOptions = [
  { value: "DRAFT", label: "Draft" },
  { value: "CONFIRMED", label: "Confirmed" },
  { value: "PACKED", label: "Packed" },
  { value: "SHIPPED", label: "Shipped" },
  { value: "DELIVERED", label: "Delivered" },
  { value: "CANCELLED", label: "Cancelled" },
];

export const reportCatalog = [
  {
    key: "inventory-summary",
    label: "Inventory Summary",
    endpoint: "/reports/inventory-summary",
    filters: ["warehouse_id", "product_id", "category_id"],
  },
  {
    key: "stock-movement",
    label: "Stock Movement",
    endpoint: "/reports/stock-movement",
    filters: ["date_from", "date_to", "warehouse_id", "product_id", "category_id"],
    dateMode: "datetime",
  },
  {
    key: "low-stock",
    label: "Low Stock",
    endpoint: "/reports/low-stock",
    filters: ["warehouse_id", "product_id", "category_id"],
  },
  {
    key: "out-of-stock",
    label: "Out Of Stock",
    endpoint: "/reports/out-of-stock",
    filters: ["warehouse_id", "product_id", "category_id"],
  },
  {
    key: "warehouse-stock",
    label: "Warehouse Stock",
    endpoint: "/reports/warehouse-stock",
    filters: ["warehouse_id", "product_id", "category_id"],
  },
  {
    key: "product-valuation",
    label: "Product Valuation",
    endpoint: "/reports/product-valuation",
    filters: ["warehouse_id", "product_id", "category_id"],
  },
  {
    key: "purchase-orders",
    label: "Purchase Orders",
    endpoint: "/reports/purchase-orders",
    filters: ["date_from", "date_to", "vendor_id", "status"],
    statusOptions: purchaseOrderStatusOptions,
  },
  {
    key: "vendor-purchase",
    label: "Vendor Purchase",
    endpoint: "/reports/vendor-purchase",
    filters: ["date_from", "date_to", "vendor_id", "status"],
    statusOptions: purchaseOrderStatusOptions,
  },
  {
    key: "sales-orders",
    label: "Sales Orders",
    endpoint: "/reports/sales-orders",
    filters: ["date_from", "date_to", "customer_id", "status"],
    statusOptions: salesOrderStatusOptions,
  },
  {
    key: "customer-sales",
    label: "Customer Sales",
    endpoint: "/reports/customer-sales",
    filters: ["date_from", "date_to", "customer_id", "status"],
    statusOptions: salesOrderStatusOptions,
  },
  {
    key: "inventory-adjustment",
    label: "Inventory Adjustments",
    endpoint: "/reports/inventory-adjustment",
    filters: ["date_from", "date_to", "warehouse_id", "product_id", "category_id"],
    dateMode: "datetime",
  },
  {
    key: "audit-logs",
    label: "Audit Logs",
    endpoint: "/reports/audit-logs",
    filters: ["date_from", "date_to", "action", "entity_type"],
    dateMode: "datetime",
  },
];
